# Rakefile
desc "Run all specs"
task :spec do
  spec_files = FileList['spec/*_spec.rb']
  spec_files.each do |file|
    ruby file
  end
end

namespace :scheduler do
  desc "Run scheduler"
  task :run do
    ruby("run.rb", ARGV[1])
  end
end